#!/usr/bin/env python3
import argparse, hashlib, json, re
from pathlib import Path

parser = argparse.ArgumentParser(); parser.add_argument('--output', type=Path, required=True); args = parser.parse_args()
root = Path(__file__).resolve().parents[1]; output = args.output.resolve()
ledger_path = root / 'third-party-notices.md'; ledger = ledger_path.read_text()
required = ['officecli', 'browser-act-cli', 'Google Chrome', 'Pillow', 'workbench.svg']
if any(name not in ledger for name in required): raise SystemExit('notice ledger incomplete')
rows = [line for line in ledger.splitlines() if line.startswith('|') and not line.startswith('| ---')]
for name in required:
 row = next((line for line in rows if name in line), '')
 fields = [field.strip() for field in row.strip('|').split('|')]
 if len(fields) < 6 or any(not field for field in fields[:6]): raise SystemExit(f'notice fields incomplete: {name}')
allowed_claims = {'本项目原创', 'MIT', 'MIT 仓库许可证', 'Apache-2.0', 'BSD', 'BSD-2-Clause', 'BSD-3-Clause', 'ISC', 'CC0', 'CC0-1.0', 'HPND', 'PIL License'}
def allowed_claim(claim):
 return claim.strip() in allowed_claims
embedded_section = ledger.split('## 2.', 1)[0]
for line in embedded_section.splitlines():
 if not line.startswith('|') or line.startswith('| ---') or line.startswith('| 名称'): continue
 fields = [field.strip() for field in line.strip('|').split('|')]
 if len(fields) < 4: raise SystemExit(f'embedded notice row incomplete: {line}')
 license_value = fields[3]
 if re.search(r'(?i)\b(?:AGPL|LGPL|GPL|MPL|EPL)\b', license_value): raise SystemExit(f'embedded license outside allowlist: {fields[0]}')
 claims = [claim.strip() for claim in re.split(r'(?i)\s+(?:AND|OR)\s+|[/,;，]', license_value) if claim.strip()]
 if any(not allowed_claim(claim) for claim in claims): raise SystemExit(f'embedded license outside allowlist: {fields[0]}')
files = []
for path in sorted(root.rglob('*')):
 if path.resolve() == output or not path.is_file(): continue
 if 'screenshots' not in path.parts and path.suffix not in ('.py', '.sh', '.svg', '.html', '.pptx', '.json', '.png'): continue
 origin = 'project implementation' if path.suffix in ('.py', '.sh') else 'project-authored asset' if path.suffix == '.svg' else 'generated by 507-ppt scripts' if path.suffix in ('.html', '.pptx', '.png') else 'verification record'
 files.append({'path': str(path.relative_to(root)), 'origin': origin, 'sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
for path in root.glob('examples/*.html'):
 if re.search(r'https?://', path.read_text()): raise SystemExit(f'remote resource: {path}')
report = {'status': 'passed', 'noticeLedger': 'third-party-notices.md', 'allowedEmbeddedLicenses': sorted(allowed_claims), 'files': files}
args.output.parent.mkdir(parents=True, exist_ok=True); args.output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n')
print('provenance passed:', len(files), 'files')
