#!/usr/bin/env python3
"""Build or verify the repository-local 507-ppt provenance ledger."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import PIL
import websockets

from browser_tools import chrome_version, find_chrome

ROOT = Path(__file__).resolve().parents[1]
LEDGER_PATH = ROOT / "third-party-notices.md"
REQUIRED = ("officecli", "Google Chrome", "Pillow", "websockets", "workbench.svg")
ALLOWED_CLAIMS = {"本项目原创", "MIT", "MIT 仓库许可证", "Apache-2.0", "BSD", "BSD-2-Clause", "BSD-3-Clause", "ISC", "CC0", "CC0-1.0", "HPND", "PIL License"}


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate_notice_ledger() -> None:
    ledger = LEDGER_PATH.read_text(encoding="utf-8")
    if any(name not in ledger for name in REQUIRED):
        raise SystemExit("notice ledger incomplete")
    rows = [line for line in ledger.splitlines() if line.startswith("|") and not line.startswith("| ---")]
    for name in REQUIRED:
        row = next((line for line in rows if name in line), "")
        fields = [field.strip() for field in row.strip("|").split("|")]
        if len(fields) < 6 or any(not field for field in fields[:6]):
            raise SystemExit(f"notice fields incomplete: {name}")
    embedded_section = ledger.split("## 2.", 1)[0]
    for line in embedded_section.splitlines():
        if not line.startswith("|") or line.startswith("| ---") or line.startswith("| 名称"):
            continue
        fields = [field.strip() for field in line.strip("|").split("|")]
        if len(fields) < 4:
            raise SystemExit(f"embedded notice row incomplete: {line}")
        license_value = fields[3]
        if re.search(r"(?i)\b(?:AGPL|LGPL|GPL|MPL|EPL)\b", license_value):
            raise SystemExit(f"embedded license outside allowlist: {fields[0]}")
        claims = [claim.strip() for claim in re.split(r"(?i)\s+(?:AND|OR)\s+|[/,;，]", license_value) if claim.strip()]
        if any(claim not in ALLOWED_CLAIMS for claim in claims):
            raise SystemExit(f"embedded license outside allowlist: {fields[0]}")


def scanned_files(excluded: Path) -> list[dict[str, str]]:
    files: list[dict[str, str]] = []
    for path in sorted(ROOT.rglob("*")):
        if path.resolve() == excluded.resolve() or not path.is_file():
            continue
        if "screenshots" not in path.parts and path.suffix not in (".py", ".sh", ".svg", ".html", ".pptx", ".json", ".png", ".txt"):
            continue
        origin = "project implementation" if path.suffix in (".py", ".sh") else "project-authored asset" if path.suffix == ".svg" else "generated by 507-ppt scripts" if path.suffix in (".html", ".pptx", ".png") else "verification record"
        files.append({"path": str(path.relative_to(ROOT)), "origin": origin, "sha256": digest(path)})
    for path in ROOT.glob("examples/*.html"):
        if re.search(r"https?://", path.read_text(encoding="utf-8")):
            raise SystemExit(f"remote resource: {path}")
    return files


def command_version(command: list[str]) -> str:
    try:
        result = subprocess.run(command, check=True, text=True, capture_output=True)
    except (OSError, subprocess.CalledProcessError):
        return "unavailable"
    return (result.stdout or result.stderr).strip()


def git_metadata() -> tuple[str, str]:
    revision = command_version(["git", "-C", str(ROOT), "rev-parse", "HEAD"])
    try:
        status = subprocess.run(["git", "-C", str(ROOT), "status", "--porcelain"], check=True, text=True, capture_output=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return revision, "unknown"
    return revision, "dirty" if status else "clean"


def build_report(output: Path) -> dict[str, Any]:
    browser = find_chrome()
    revision, worktree_status = git_metadata()
    return {
        "status": "passed",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "gitRevision": revision,
        "worktreeStatus": worktree_status,
        "generatorSha256": digest(Path(__file__)),
        "noticeLedger": "third-party-notices.md",
        "noticeLedgerSha256": digest(LEDGER_PATH),
        "allowedEmbeddedLicenses": sorted(ALLOWED_CLAIMS),
        "tools": {
            "officecli": command_version(["officecli", "--version"]),
            "browser": chrome_version(browser) if browser else "unavailable",
            "Pillow": PIL.__version__,
            "websockets": websockets.__version__,
        },
        "files": scanned_files(output),
    }


def check_report(path: Path) -> None:
    try:
        stored = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise SystemExit(f"provenance report is unreadable: {path}") from error
    if stored.get("status") != "passed" or not all(stored.get(key) for key in ("generatedAt", "gitRevision", "generatorSha256", "tools", "noticeLedgerSha256", "files")):
        raise SystemExit("provenance report metadata is incomplete")
    if stored["generatorSha256"] != digest(Path(__file__)):
        raise SystemExit("provenance report generator source hash is stale")
    if stored["noticeLedgerSha256"] != digest(LEDGER_PATH):
        raise SystemExit("provenance notice ledger hash is stale")
    expected = scanned_files(path)
    if stored.get("files") != expected:
        old = {item.get("path"): item.get("sha256") for item in stored.get("files") or []}
        new = {item["path"]: item["sha256"] for item in expected}
        changed = sum(file_path in new and new[file_path] != value for file_path, value in old.items())
        missing = sum(file_path not in old for file_path in new)
        removed = sum(file_path not in new for file_path in old)
        raise SystemExit(f"provenance report is stale: changed={changed}, missing={missing}, removed={removed}")
    print(f"provenance report passed: {path} ({len(expected)} files)")


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--output", type=Path)
    mode.add_argument("--check", type=Path)
    args = parser.parse_args()
    validate_notice_ledger()
    if args.check:
        check_report(args.check.resolve())
        return
    output = args.output.resolve()
    report = build_report(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("provenance passed:", len(report["files"]), "files")


if __name__ == "__main__":
    main()
